//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERMISOS
    {
        public int IDPERMISOS { get; set; }
        public Nullable<int> IDEMPLEADO { get; set; }
        public Nullable<int> IDPERFIL { get; set; }
    
        public virtual TBL_EMPLEADO TBL_EMPLEADO { get; set; }
        public virtual TBL_PERFIL TBL_PERFIL { get; set; }
    }
}
