//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EXPEDIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_EXPEDIENTE()
        {
            this.TBL_DET_EXPEDIENTE = new HashSet<TBL_DET_EXPEDIENTE>();
        }
    
        public int IDEXPEDIENTE { get; set; }
        public Nullable<short> AÑO { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> IDTIPO_DOCUMENTO { get; set; }
        public string NRO_DOCUMENTO { get; set; }
        public System.DateTime FEC_RECEPCION { get; set; }
        public Nullable<int> IDSOLICITANTE { get; set; }
        public string ASUNTO { get; set; }
        public int FOLIOS { get; set; }
        public string OBSERVACION { get; set; }
        public string CLAVE_WEB { get; set; }
        public string NRO_EXPEDIENTE { get; set; }
        public string IDESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DET_EXPEDIENTE> TBL_DET_EXPEDIENTE { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
        public virtual TBL_TIPO_DOCUMENTO TBL_TIPO_DOCUMENTO { get; set; }
    }
}
