//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OFICINA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_OFICINA()
        {
            this.TBL_DET_EXPEDIENTE = new HashSet<TBL_DET_EXPEDIENTE>();
            this.TBL_DET_EXPEDIENTE1 = new HashSet<TBL_DET_EXPEDIENTE>();
            this.TBL_EMPLEADO = new HashSet<TBL_EMPLEADO>();
            this.TBL_TUPA = new HashSet<TBL_TUPA>();
        }
    
        public int IDOFICINA { get; set; }
        public string OFICINA { get; set; }
        public string SIGLA { get; set; }
        public string SIGLA_DOC { get; set; }
        public Nullable<bool> FLGESTADO { get; set; }
        public Nullable<int> USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
        public Nullable<int> USU_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FEC_MODIFICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DET_EXPEDIENTE> TBL_DET_EXPEDIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DET_EXPEDIENTE> TBL_DET_EXPEDIENTE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_EMPLEADO> TBL_EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TUPA> TBL_TUPA { get; set; }
    }
}
