//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PERSONA()
        {
            this.TBL_EXPEDIENTE = new HashSet<TBL_EXPEDIENTE>();
            this.TBL_SOLICITANTE = new HashSet<TBL_SOLICITANTE>();
        }
    
        public int IDPERSONA { get; set; }
        public string TIPO { get; set; }
        public string NOMBRE { get; set; }
        public string APEPATERNO { get; set; }
        public string APEMATERNO { get; set; }
        public string DNI { get; set; }
        public string RUC { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
        public string CELULAR { get; set; }
        public Nullable<int> USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
        public Nullable<int> USU_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FEC_MODIFICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_EXPEDIENTE> TBL_EXPEDIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SOLICITANTE> TBL_SOLICITANTE { get; set; }
    }
}
