//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TUPA_REQUISITO
    {
        public int IDTUPA_REQUISITO { get; set; }
        public Nullable<int> IDTUPA { get; set; }
        public Nullable<int> IDREQUISITO { get; set; }
    
        public virtual TBL_REQUISITO TBL_REQUISITO { get; set; }
        public virtual TBL_TUPA TBL_TUPA { get; set; }
    }
}
