//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SOLICITANTE
    {
        public int IDSOLICITANTE { get; set; }
        public Nullable<int> IDPERSONA { get; set; }
        public Nullable<bool> FLGESTADO { get; set; }
    
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
    }
}
