//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_EMPLEADO()
        {
            this.TBL_PERMISOS = new HashSet<TBL_PERMISOS>();
        }
    
        public int IDEMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string APEPATERNO { get; set; }
        public string APEMATERNO { get; set; }
        public string DNI { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
        public string CELULAR { get; set; }
        public Nullable<int> IDCARGO { get; set; }
        public Nullable<int> IDOFICINA { get; set; }
        public Nullable<System.DateTime> FEC_INGRESO { get; set; }
        public Nullable<System.DateTime> FEC_FINAL { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> FLGESTADO { get; set; }
        public string FOTO { get; set; }
    
        public virtual TBL_CARGO TBL_CARGO { get; set; }
        public virtual TBL_OFICINA TBL_OFICINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PERMISOS> TBL_PERMISOS { get; set; }
    }
}
