//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPRESA
    {
        public int IDEMPRESA { get; set; }
        public string EMPRESA { get; set; }
        public string SIGLA { get; set; }
        public string RUC { get; set; }
        public string DIRECCION { get; set; }
        public string WEB { get; set; }
        public string TELEFONO { get; set; }
        public string SLOGAN { get; set; }
        public string CORREO { get; set; }
        public string PASSWORD { get; set; }
        public string HOST { get; set; }
        public Nullable<int> PORT { get; set; }
    }
}
