//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DET_EXPEDIENTE
    {
        public int IDDET_EXPEDIENTE { get; set; }
        public Nullable<int> IDEXPEDIENTE { get; set; }
        public Nullable<int> IDCORRELATIVO { get; set; }
        public Nullable<System.DateTime> FEC_RECEPCION { get; set; }
        public string OBS_RECEPCION { get; set; }
        public Nullable<System.DateTime> FEC_DERIVACION { get; set; }
        public string OBS_DERIVACION { get; set; }
        public string ESTADO { get; set; }
        public string DOC_ADJUNTADO { get; set; }
        public Nullable<int> IDREMITENTE_E { get; set; }
        public Nullable<int> IDREMITENTE_I { get; set; }
        public Nullable<int> IDDESTINO_E { get; set; }
        public Nullable<int> IDDESTINO_I { get; set; }
        public string TIPO { get; set; }
        public string PRIORIDAD { get; set; }
        public Nullable<System.DateTime> FEC_ENVIO { get; set; }
        public Nullable<System.DateTime> FEC_FINALIZAR { get; set; }
        public string OBS_FINALIZAR { get; set; }
        public Nullable<System.DateTime> FEC_ARCHIVAR { get; set; }
        public string OBS_ARCHIVAR { get; set; }
        public string UBIC_ARCHIVO { get; set; }
        public string USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
    
        public virtual TBL_OFICINA TBL_OFICINA { get; set; }
        public virtual TBL_EXPEDIENTE TBL_EXPEDIENTE { get; set; }
        public virtual TBL_OFICINA TBL_OFICINA1 { get; set; }
    }
}
