//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TIPO_DOCUMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TIPO_DOCUMENTO()
        {
            this.TBL_EXPEDIENTE = new HashSet<TBL_EXPEDIENTE>();
        }
    
        public int IDTIPO_DOCUMENTO { get; set; }
        public string TIPODOCUMENTO { get; set; }
        public string SIGLA { get; set; }
        public Nullable<bool> FLGESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_EXPEDIENTE> TBL_EXPEDIENTE { get; set; }
    }
}
